### ISSUE TITLE
link shows 404

### ISSUE THREAD

**Issue by cijagani** [cloudpanel-io/clp-opcache-preloader#2]
follwoing link shows 404 and this link is mentioned in read me file
https://www.cloudpanel.io/docs/cloudpanel-ce/guides/php/opcache-preload

**Comment by yasershahi** [comment]
https://web.archive.org/web/20210613163748/https://www.cloudpanel.io/docs/cloudpanel-ce/guides/php/opcache-preload

just to see what was in there
